import json,os,time
from http.server import BaseHTTPRequestHandler,HTTPServer
ROOT=os.path.expanduser("~/btc_fisher_trader")
FILES={"edge":ROOT+"/data/processed/edge_lab_summary_v1.json","forecast":ROOT+"/data/processed/forecast_calibration_v2.json","scalper":ROOT+"/data/processed/pro_scalper_v4_summary.json","micro":ROOT+"/data/processed/microstructure_scalper_v2_live_summary.json","professional":ROOT+"/data/processed/professional_paper_v1_summary.json"}
def load(p):
 try:
  with open(p) as f:return json.load(f)
 except:return {"status":"NO_DATA"}
HTML='''<!doctype html><html><head><meta name="viewport" content="width=device-width,initial-scale=1"><title>BTC Research Command</title><style>body{font-family:system-ui;background:#0b0e12;color:#eee;margin:0;padding:14px}h1{font-size:22px}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(280px,1fr));gap:12px}.card{background:#151a21;border:1px solid #29313b;border-radius:12px;padding:14px}.k{color:#8fa1b5;font-size:12px}.v{font-size:20px;font-weight:700;margin:4px 0 10px}.row{display:flex;justify-content:space-between;border-bottom:1px solid #252c35;padding:7px 0}.warn{font-size:12px;color:#ffcc66}</style></head><body><h1>BTC Professional Scalper — Research Command</h1><div class="card"><div class="k">EXECUTION</div><div class="v">PAPER ONLY · REAL ORDERS DISABLED</div><div id="fresh"></div></div><div class="grid"><div class="card"><h3>Edge Lab</h3><div id="edge"></div></div><div class="card"><h3>Forecast Calibration</h3><div id="forecast"></div></div><div class="card"><h3>Professional Scalper V4</h3><div id="scalper"></div></div><div class="card"><h3>Other Paper Engines</h3><pre id="other"></pre></div></div><script>const row=(k,v)=>'<div class="row"><span class="k">'+k+'</span><b>'+v+'</b></div>';async function r(){let d=await fetch('/api/research?'+Date.now()).then(x=>x.json());let age=d.microstructure_age_s;document.getElementById('fresh').innerHTML=row('Data age',age==null?'unknown':age.toFixed(2)+'s')+(age>5?'<div class="warn">STALE DATA — validation paused</div>':'<div class="k">Live-data quality acceptable</div>');let e=d.edge_lab||{},o=e.opportunities||{},s=e.strategies||{};document.getElementById('edge').innerHTML=row('Flow',o.flow_continuation||'—')+row('Absorption',o.absorption_reversal||'—')+row('Cross venue',o.cross_venue_confirmation||'—')+row('Flow + AI',o.flow_ai_cost_filter||'—')+Object.entries(s).map(([k,v])=>row(k,(v.n||0)+' completed')).join('');let f=d.forecast||{},fs=f.stats||{};document.getElementById('forecast').innerHTML=row('Status',f.status||'UNVALIDATED')+row('30s',(fs['30']?.n||0)+' / 100')+row('60s',(fs['60']?.n||0)+' / 100')+row('30s active',(fs['30']?.active_n||0)) +row('60s active',(fs['60']?.active_n||0));let p=d.pro_scalper_v4||{};document.getElementById('scalper').innerHTML=row('Signals',p.paper_signals??0)+row('LONG',p.long??0)+row('SHORT',p.short??0)+row('NO TRADE',p.no_trade??0)+row('Avg net edge',((p.avg_net_edge_bps??0))+' bps');document.getElementById('other').textContent=JSON.stringify({microstructure_v2:d.microstructure_v2,professional_paper:d.professional_paper},null,2)}r();setInterval(r,2000)</script></body></html>'''
class H(BaseHTTPRequestHandler):
 def log_message(self,*a):pass
 def do_GET(self):
  if self.path.startswith('/api/research'):
   age=time.time()-float(load(ROOT+'/data/live_microstructure_state.json').get('timestamp',0))
   body=json.dumps({"timestamp":time.time(),"microstructure_age_s":age,"paper_only":True,"order_submission":False,"edge_lab":load(FILES["edge"]),"forecast":load(FILES["forecast"]),"pro_scalper_v4":load(FILES["scalper"]),"microstructure_v2":load(FILES["micro"]),"professional_paper":load(FILES["professional"])}).encode()
   self.send_response(200);self.send_header('Content-Type','application/json');self.send_header('Cache-Control','no-store');self.end_headers();self.wfile.write(body);return
  self.send_response(200);self.send_header('Content-Type','text/html; charset=utf-8');self.end_headers();self.wfile.write(HTML.encode())
HTTPServer(('0.0.0.0',8790),H).serve_forever()
