import { IndicatorDefinition } from '../types/microstructure';

export const INITIAL_RESEARCH_INDICATORS: IndicatorDefinition[] = [
  {
    id: 'ind-001',
    name: 'Rolling Delta Imbalance',
    version: '1.0.0',
    formula: 'RDI(w) = sum(SignedDelta, w) / sum(TotalVolume, w)',
    description: 'Measures net aggressive market buy volume relative to total volume over a rolling window w.',
    requiredFields: ['buyVolume', 'sellVolume', 'volume'],
    parameters: {
      rollingWindow: 14,
      threshold: 0.15,
      smoothing: 'SMA',
    },
    calculationTimeframe: '1m',
    warmupPeriod: 14,
    signalDefinition: {
      longCondition: 'RDI(14) > 0.15',
      shortCondition: 'RDI(14) < -0.15',
      exitCondition: 'abs(RDI) < 0.05',
    },
    missingDataBehavior: 'drop_and_warn',
    status: 'RESEARCHING',
    createdAt: Date.now() - 86400000 * 3,
    validationMetrics: {
      inSampleHitRate: 53.2,
      outOfSampleHitRate: 50.8,
      outOfSampleIC: 0.042,
      outOfSamplePValue: 0.18,
      sampleSize: 180,
    },
  },
  {
    id: 'ind-002',
    name: 'Normalized Order-Book Imbalance',
    version: '1.2.0',
    formula: 'NOBI(k) = (BidDepth(k) - AskDepth(k)) / (BidDepth(k) + AskDepth(k))',
    description: 'Calculates the relative supply/demand pressure across the top k levels of the reconstructed L2 order book.',
    requiredFields: ['bids', 'asks', 'depthImbalance10'],
    parameters: {
      depthLevels: 10,
      threshold: 0.25,
      decayFactor: 0.95,
    },
    calculationTimeframe: 'Tick / 1m',
    warmupPeriod: 5,
    signalDefinition: {
      longCondition: 'NOBI(10) > 0.25',
      shortCondition: 'NOBI(10) < -0.25',
      exitCondition: 'crosses(NOBI, 0)',
    },
    missingDataBehavior: 'hold_last',
    status: 'IN_SAMPLE_VALIDATED',
    createdAt: Date.now() - 86400000 * 5,
    lastValidatedAt: Date.now() - 86400000,
    validationMetrics: {
      inSampleHitRate: 55.4,
      outOfSampleHitRate: 52.1,
      outOfSampleIC: 0.068,
      outOfSamplePValue: 0.045,
      sampleSize: 220,
    },
  },
  {
    id: 'ind-003',
    name: 'Trade-Flow Acceleration',
    version: '1.0.1',
    formula: 'TFA(w) = d/dt (RollingDelta(w))',
    description: 'Second derivative of signed volume delta, identifying aggressive momentum surges before price reaction.',
    requiredFields: ['signedDelta', 'rollingDeltaAcceleration'],
    parameters: {
      fastWindow: 5,
      slowWindow: 15,
      accelerationThreshold: 2.5,
    },
    calculationTimeframe: '1m',
    warmupPeriod: 20,
    signalDefinition: {
      longCondition: 'TFA > 2.5 && SignedDelta > 0',
      shortCondition: 'TFA < -2.5 && SignedDelta < 0',
      exitCondition: 'TFA changes sign',
    },
    missingDataBehavior: 'drop_and_warn',
    status: 'EXPERIMENTAL',
    createdAt: Date.now() - 86400000 * 2,
    validationMetrics: {
      inSampleHitRate: 51.0,
      outOfSampleHitRate: 49.2,
      outOfSampleIC: -0.015,
      outOfSamplePValue: 0.42,
      sampleSize: 150,
    },
  },
  {
    id: 'ind-004',
    name: 'Delta-Price Divergence',
    version: '2.0.0',
    formula: 'DPD = sign(Delta) * (1 - sign(dPrice))',
    description: 'Identifies aggressive market orders being absorbed by passive limit orders at key support/resistance.',
    requiredFields: ['close', 'signedDelta', 'deltaPriceDivergence'],
    parameters: {
      priceChangeThresholdBps: 5,
      deltaQuantile: 0.8,
    },
    calculationTimeframe: '1m',
    warmupPeriod: 10,
    signalDefinition: {
      longCondition: 'PriceFalling && SignedDelta > 0.8 Quantile (Absorption)',
      shortCondition: 'PriceRising && SignedDelta < 0.2 Quantile (Exhaustion)',
      exitCondition: 'Fixed 5-minute horizon',
    },
    missingDataBehavior: 'interpolate',
    status: 'RESEARCHING',
    createdAt: Date.now() - 86400000 * 6,
    validationMetrics: {
      inSampleHitRate: 56.8,
      outOfSampleHitRate: 51.5,
      outOfSampleIC: 0.051,
      outOfSamplePValue: 0.082,
      sampleSize: 210,
    },
  },
  {
    id: 'ind-005',
    name: 'Liquidity Pressure Index',
    version: '1.0.0',
    formula: 'LPI = (Microprice - Midprice) / Spread',
    description: 'Microstructure displacement of volume-weighted microprice normalized by current bid-ask spread.',
    requiredFields: ['microprice', 'midPrice', 'spread'],
    parameters: {
      spreadBpsCap: 15,
      pressureThreshold: 0.35,
    },
    calculationTimeframe: 'Tick / 1m',
    warmupPeriod: 1,
    signalDefinition: {
      longCondition: 'LPI > 0.35',
      shortCondition: 'LPI < -0.35',
      exitCondition: 'abs(LPI) < 0.1',
    },
    missingDataBehavior: 'hold_last',
    status: 'DRAFT',
    createdAt: Date.now() - 86400000 * 1,
  },
  {
    id: 'ind-006',
    name: 'Flow Persistence Metric',
    version: '1.1.0',
    formula: 'FP(k) = Autocorrelation(SignedDelta, lag=k)',
    description: 'Tracks whether trade flow exhibits clustering / institutional iceberg execution behavior.',
    requiredFields: ['signedDelta', 'flowPersistence'],
    parameters: {
      lag: 1,
      window: 30,
    },
    calculationTimeframe: '1m',
    warmupPeriod: 30,
    signalDefinition: {
      longCondition: 'FP > 0.4 && SignedDelta > 0',
      shortCondition: 'FP > 0.4 && SignedDelta < 0',
      exitCondition: 'FP < 0.1',
    },
    missingDataBehavior: 'drop_and_warn',
    status: 'RESEARCHING',
    createdAt: Date.now() - 86400000 * 4,
  },
  {
    id: 'ind-007',
    name: 'Volume-Weighted Order-Flow Pressure',
    version: '1.0.0',
    formula: 'VWOFP = SignedDelta * (1 / (1 + SpreadBps))',
    description: 'Penalizes delta signals during wide spread / illiquid market regimes.',
    requiredFields: ['signedDelta', 'spreadBps'],
    parameters: {
      baseSpread: 2.0,
      scaleFactor: 1.0,
    },
    calculationTimeframe: '1m',
    warmupPeriod: 5,
    signalDefinition: {
      longCondition: 'VWOFP > 10.0',
      shortCondition: 'VWOFP < -10.0',
      exitCondition: 'abs(VWOFP) < 2.0',
    },
    missingDataBehavior: 'drop_and_warn',
    status: 'REJECTED',
    createdAt: Date.now() - 86400000 * 10,
    validationMetrics: {
      inSampleHitRate: 48.5,
      outOfSampleHitRate: 46.2,
      outOfSampleIC: -0.035,
      outOfSamplePValue: 0.65,
      sampleSize: 190,
    },
  },
  {
    id: 'ind-008',
    name: 'Combined Delta & Liquidity Signal',
    version: '2.1.0',
    formula: 'CDLS = 0.6 * Normal(RDI) + 0.4 * Normal(NOBI)',
    description: 'Multivariate composite signal requiring confluence of aggressive trade delta and passive limit book skew.',
    requiredFields: ['signedDelta', 'depthImbalance10', 'volume'],
    parameters: {
      deltaWeight: 0.6,
      bookWeight: 0.4,
      threshold: 0.22,
    },
    calculationTimeframe: '1m',
    warmupPeriod: 20,
    signalDefinition: {
      longCondition: 'CDLS > 0.22',
      shortCondition: 'CDLS < -0.22',
      exitCondition: 'abs(CDLS) < 0.05',
    },
    missingDataBehavior: 'drop_and_warn',
    status: 'OUT_OF_SAMPLE_VALIDATED',
    createdAt: Date.now() - 86400000 * 14,
    lastValidatedAt: Date.now() - 86400000 * 2,
    validationMetrics: {
      inSampleHitRate: 58.2,
      outOfSampleHitRate: 54.1,
      outOfSampleIC: 0.089,
      outOfSamplePValue: 0.018,
      sampleSize: 240,
    },
  },
];
